name: Update README ⭐
on:
    push:
    schedule:
      - cron: "0 0 * * *"  # Everyday at midnight
    workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 906886
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2022
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars
